select = ["F","W","E","C90","I","N","D","UP","YTT","ANN","ASYNC","BLE","B","A","COM","CPY","C4","DTZ","T10","DJ","EM","EXE","FA","ISC","ICN","G","INP","PIE","PYI","PT","Q","RSE","RET","SLF","SLOT","SIM","TID","TCH","INT","ARG","PTH"]
ignore = ["ANN101", "ANN102", "E203", "S", "FBT", "T20"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
#fixable = ["ALL"]
#unfixable = []

include = ["black_it/**/*.py", "tests/**/*.py", "scripts/**/*.py", "examples/**/*.py"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "scripts/whitelists/*"
]

# Same as Black.
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Whether to enable preview mode. When preview mode is enabled, Ruff will use unstable rules and fixes.
preview = true

# Assume Python 3.8
target-version = "py38"

[per-file-ignores]
"examples/docker-sir.py" = ["INP001", "T201"]
"examples/main.py" = ["INP001", "T201"]
"examples/models/simple_models.py" = ["INP001"]
"examples/models/forest_fire/forest_fire.py" = ["T201"]
"examples/models/sir/simlib.py" = ["T201"]
"scripts/check_copyright.py" = ["T201"]


[mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[pydocstyle]
convention = "google"
