select = [
  "A",
  "AIR",
  "ANN",
  "ARG",
  "ASYNC",
  "B",
  "BLE",
  "C4",
  "C90",
  "COM",
  "CPY",
  "D",
  "DJ",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "EXE",
  "F",
  "FA",
  "FIX",
  "FLY",
  "FURB",
  "G",
  "I",
  "ICN",
  "INP",
  "INT",
  "ISC",
  "LOG",
  "N",
  "NPY",
  "PD",
  "PERF",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RET",
  "RSE",
  "RUF",
  "SIM",
  "SLF",
  "SLOT",
  "T10",
  "TCH",
  "TD",
  "TID",
  "TRY",
  "UP",
  "W",
  "YTT",
]
ignore = [
  "ANN101",
  "ANN102",
  "E203",
  "FBT",
  "S",
  "T20",
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
#fixable = ["ALL"]
#unfixable = []

include = [
  "black_it/**/*.py",
  "examples/**/*.py",
  "scripts/**/*.py",
  "tests/**/*.py",
]

# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "scripts/whitelists/*",
  "venv",
]

# Same as Black.
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Whether to enable preview mode. When preview mode is enabled, Ruff will use unstable rules and fixes.
preview = true

# Assume Python 3.9
target-version = "py39"

[per-file-ignores]
"examples/docker-sir.py" = ["INP001", "T201"]
"examples/main.py" = ["INP001", "T201"]
"examples/models/economics/brock_hommes.py" = ["ERA001"]
"examples/models/forest_fire/forest_fire.py" = ["T201"]
"examples/models/simple_models.py" = ["ERA001", "INP001"]
"examples/models/sir/simlib.py" = ["T201"]
"scripts/check_copyright.py" = ["T201"]
"tests/**.py" = ["PLR2004"]


[mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[pydocstyle]
convention = "google"

[pylint]
max-args = 7
